// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NainConfigurator.Infrastructure.Persistence;

#nullable disable

namespace NainConfigurator.Infrastructure.Migrations
{
    [DbContext(typeof(NainConfiguratorDbContext))]
    partial class NainConfiguratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompanyBrandProfileEntity", b =>
                {
                    b.Property<long>("CompanyBrandProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CompanyBrandProfileId"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("LogoAssetKey")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("OnPrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("CompanyBrandProfileId")
                        .HasName("PK_CompanyBrandProfiles");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CompanyBrandProfiles_CompanyId");

                    b.HasIndex("CompanyId", "CompanyBrandProfileId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CompanyBrandProfiles_Company_Profile");

                    b.ToTable("CompanyBrandProfiles", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_CompanyBrandProfiles_Colors", "[PrimaryColor] LIKE '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]' COLLATE Latin1_General_100_BIN2 AND [OnPrimaryColor] LIKE '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_CompanyBrandProfiles_Mode", "[Mode] = 'CoBranded'");

                            t.HasCheckConstraint("CK_CompanyBrandProfiles_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompanyEntity", b =>
                {
                    b.Property<long>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CompanyId"));

                    b.Property<long?>("ActivePrivacyPolicyId")
                        .HasColumnType("bigint");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("CompanyId")
                        .HasName("PK_Companies");

                    b.HasAlternateKey("Slug")
                        .HasName("AK_Companies_Slug");

                    b.HasIndex("ActivePrivacyPolicyId", "CompanyId");

                    b.ToTable("Companies", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Companies_DisplayNameLength", "LEN([DisplayName]) BETWEEN 1 AND 150");

                            t.HasCheckConstraint("CK_Companies_SlugFormat", "LEN([Slug]) BETWEEN 1 AND 100 AND [Slug] NOT LIKE '%[^a-z0-9-]%' COLLATE Latin1_General_100_BIN2");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompanyPrivacyPolicyEntity", b =>
                {
                    b.Property<long>("CompanyPrivacyPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CompanyPrivacyPolicyId"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentAssetKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<byte[]>("ContentHashSha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<short>("QuoteRetentionDays")
                        .HasColumnType("smallint");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("CompanyPrivacyPolicyId")
                        .HasName("PK_CompanyPrivacyPolicies");

                    b.HasAlternateKey("CompanyPrivacyPolicyId", "CompanyId")
                        .HasName("AK_CompanyPrivacyPolicies_Policy_Company");

                    b.HasIndex("CompanyId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UQ_CompanyPrivacyPolicies_Company_Version");

                    b.ToTable("CompanyPrivacyPolicies", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_CompanyPrivacyPolicies_ResourceUrl", "LEN([ResourceUrl]) BETWEEN 1 AND 2048 AND [ResourceUrl] LIKE 'https://%'");

                            t.HasCheckConstraint("CK_CompanyPrivacyPolicies_Retention", "[QuoteRetentionDays] BETWEEN 30 AND 1825");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleEntity", b =>
                {
                    b.Property<long>("CompatibilityRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CompatibilityRuleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("CompatibilityRuleId")
                        .HasName("PK_CompatibilityRules");

                    b.HasAlternateKey("CompanyId", "ProductId", "CompatibilityRuleId")
                        .HasName("AK_CompatibilityRules_Company_Product_Rule");

                    b.HasIndex("CompanyId", "ProductId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_CompatibilityRules_Company_Product_Code");

                    b.ToTable("CompatibilityRules", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_CompatibilityRules_Type", "[Type] = 'RequiresAny'");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleSourceEntity", b =>
                {
                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompatibilityRuleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductOptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("CompanyId", "CompatibilityRuleId", "ProductOptionId")
                        .HasName("PK_CompatibilityRuleSources");

                    b.HasIndex("CompanyId", "ProductId", "CompatibilityRuleId");

                    b.HasIndex("CompanyId", "ProductId", "ProductOptionId");

                    b.ToTable("CompatibilityRuleSources", "catalog");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleTargetEntity", b =>
                {
                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompatibilityRuleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductOptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("CompanyId", "CompatibilityRuleId", "ProductOptionId")
                        .HasName("PK_CompatibilityRuleTargets");

                    b.HasIndex("CompanyId", "ProductId", "CompatibilityRuleId");

                    b.HasIndex("CompanyId", "ProductId", "ProductOptionId");

                    b.ToTable("CompatibilityRuleTargets", "catalog");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ConfigurationEntity", b =>
                {
                    b.Property<long>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConfigurationId"));

                    b.Property<int>("CatalogVersionAtCreation")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CompanySlugSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ConfigurationCode")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("char(28)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ContentLocale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<decimal>("EstimatedPrice")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<byte>("FingerprintVersion")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("IdempotencyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<decimal>("ProductBasePriceSnapshot")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("ProductCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("VisualStateJson")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<short?>("VisualStateSchemaVersion")
                        .HasColumnType("smallint");

                    b.HasKey("ConfigurationId")
                        .HasName("PK_Configurations");

                    b.HasAlternateKey("CompanyId", "ConfigurationId")
                        .HasName("AK_Configurations_Company_Configuration");

                    b.HasIndex("ConfigurationCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Configurations_Code");

                    b.HasIndex("CompanyId", "ProductId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Configurations_Idempotency");

                    b.ToTable("Configurations", "sales", t =>
                        {
                            t.HasCheckConstraint("CK_Configurations_Code", "LEN([ConfigurationCode]) = 28 AND [ConfigurationCode] LIKE 'NCF-%' AND SUBSTRING([ConfigurationCode], 5, 24) NOT LIKE '%[^0-9A-F]%' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_Configurations_Prices", "[ProductBasePriceSnapshot] >= 0 AND [EstimatedPrice] >= 0");

                            t.HasCheckConstraint("CK_Configurations_VisualState", "([VisualStateJson] IS NULL AND [VisualStateSchemaVersion] IS NULL) OR ([VisualStateJson] IS NOT NULL AND [VisualStateSchemaVersion] = 1 AND ISJSON([VisualStateJson]) = 1 AND DATALENGTH([VisualStateJson]) <= 32768)");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ConfigurationPriceComponentEntity", b =>
                {
                    b.Property<long>("ConfigurationPriceComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConfigurationPriceComponentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("CodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<short>("Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("ConfigurationPriceComponentId")
                        .HasName("PK_ConfigurationPriceComponents");

                    b.HasIndex("CompanyId", "ConfigurationId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigurationPriceComponents_Base")
                        .HasFilter("[Type] = 'BasePrice'");

                    b.HasIndex("CompanyId", "ConfigurationId", "Position")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigurationPriceComponents_Position");

                    b.ToTable("ConfigurationPriceComponents", "sales", t =>
                        {
                            t.HasCheckConstraint("CK_ConfigurationPriceComponents_Amount", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_ConfigurationPriceComponents_Position", "[Position] BETWEEN 0 AND 500 AND ([Type] <> 'BasePrice' OR [Position] = 0)");

                            t.HasCheckConstraint("CK_ConfigurationPriceComponents_Type", "[Type] IN ('BasePrice', 'OptionAdjustment')");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ConfigurationSelectionSnapshotEntity", b =>
                {
                    b.Property<long>("ConfigurationSelectionSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConfigurationSelectionSnapshotId"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<short>("NormalizedPosition")
                        .HasColumnType("smallint");

                    b.Property<string>("OptionCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("OptionGroupCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("OptionGroupNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OptionNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("PriceAdjustmentSnapshot")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("VisualAssetKeySnapshot")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("ConfigurationSelectionSnapshotId")
                        .HasName("PK_ConfigurationSelectionSnapshots");

                    b.HasIndex("CompanyId", "ConfigurationId", "NormalizedPosition")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigurationSelections_Position");

                    b.HasIndex("CompanyId", "ConfigurationId", "OptionCodeSnapshot")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigurationSelections_Option");

                    b.ToTable("ConfigurationSelectionSnapshots", "sales", t =>
                        {
                            t.HasCheckConstraint("CK_ConfigurationSelectionSnapshots_Amount", "[PriceAdjustmentSnapshot] >= 0");

                            t.HasCheckConstraint("CK_ConfigurationSelectionSnapshots_Position", "[NormalizedPosition] BETWEEN 0 AND 499");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.OptionGroupEntity", b =>
                {
                    b.Property<long>("OptionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OptionGroupId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short?>("MaxSelections")
                        .HasColumnType("smallint");

                    b.Property<short>("MinSelections")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("OptionGroupId")
                        .HasName("PK_OptionGroups");

                    b.HasAlternateKey("CompanyId", "ProductId", "OptionGroupId")
                        .HasName("AK_OptionGroups_Company_Product_Group");

                    b.HasIndex("CompanyId", "ProductId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_OptionGroups_Company_Product_Code");

                    b.ToTable("OptionGroups", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_OptionGroups_SelectionLimits", "[MinSelections] >= 0 AND ([MaxSelections] IS NULL OR ([MaxSelections] BETWEEN 1 AND 500 AND [MinSelections] <= [MaxSelections]))");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ProductEntity", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<int>("CatalogVersion")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PriceDisclaimer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("VisualAssetKey")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("ProductId")
                        .HasName("PK_Products");

                    b.HasAlternateKey("CompanyId", "ProductId")
                        .HasName("AK_Products_Company_Product");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Products_Company_Code");

                    b.ToTable("Products", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Products_BasePrice", "[BasePrice] >= 0");

                            t.HasCheckConstraint("CK_Products_Code", "LEN([Code]) BETWEEN 1 AND 50 AND [Code] NOT LIKE '%[^A-Z0-9_-]%' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_Products_Currency", "[CurrencyCode] LIKE '[A-Z][A-Z][A-Z]' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_Products_PublishedVersion", "[IsPublished] = 0 OR [CatalogVersion] > 0");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ProductOptionEntity", b =>
                {
                    b.Property<long>("ProductOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductOptionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("OptionGroupId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PriceAdjustment")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("VisualAssetKey")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("ProductOptionId")
                        .HasName("PK_ProductOptions");

                    b.HasAlternateKey("CompanyId", "ProductId", "ProductOptionId")
                        .HasName("AK_ProductOptions_Company_Product_Option");

                    b.HasIndex("CompanyId", "ProductId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProductOptions_Company_Product_Code");

                    b.HasIndex("CompanyId", "ProductId", "OptionGroupId");

                    b.ToTable("ProductOptions", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ProductOptions_PriceAdjustment", "[PriceAdjustment] >= 0");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.QuoteNotificationOutboxEntity", b =>
                {
                    b.Property<long>("QuoteNotificationOutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QuoteNotificationOutboxId"));

                    b.Property<short>("AttemptCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LeaseOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NotificationIntentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("QuoteRequestId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("QuoteNotificationOutboxId")
                        .HasName("PK_QuoteNotificationOutbox");

                    b.HasIndex("NotificationIntentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuoteNotificationOutbox_Intent");

                    b.HasIndex("CompanyId", "QuoteRequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuoteNotificationOutbox_Quote");

                    b.ToTable("QuoteNotificationOutbox", "operations", t =>
                        {
                            t.HasCheckConstraint("CK_QuoteNotificationOutbox_Attempts", "[AttemptCount] >= 0");

                            t.HasCheckConstraint("CK_QuoteNotificationOutbox_CompletedLease", "[CompletedAtUtc] IS NULL OR ([LeaseOwnerId] IS NULL AND [LeaseExpiresAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_QuoteNotificationOutbox_Lease", "([LeaseOwnerId] IS NULL AND [LeaseExpiresAtUtc] IS NULL) OR ([LeaseOwnerId] IS NOT NULL AND [LeaseExpiresAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.QuoteRequestEntity", b =>
                {
                    b.Property<long>("QuoteRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QuoteRequestId"));

                    b.Property<byte[]>("AcknowledgedPrivacyContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<string>("AcknowledgedPrivacyPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyPrivacyPolicyId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(508)
                        .HasColumnType("nvarchar(508)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("FingerprintVersion")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("IdempotencyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<string>("LegalHoldOwnerRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalHoldReasonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LegalHoldReviewAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LegalHoldStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalHoldTicketRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LegalHoldUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("PrivacyNoticeAcknowledged")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PrivacyNoticeAcknowledgedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("QuoteRequestCode")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("char(28)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("RetentionUntilUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("QuoteRequestId")
                        .HasName("PK_QuoteRequests");

                    b.HasAlternateKey("CompanyId", "QuoteRequestId")
                        .HasName("AK_QuoteRequests_Company_Quote");

                    b.HasIndex("QuoteRequestCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuoteRequests_Code");

                    b.HasIndex("CompanyId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_QuoteRequests_Idempotency");

                    b.HasIndex("CompanyId", "ConfigurationId");

                    b.HasIndex("CompanyPrivacyPolicyId", "CompanyId");

                    b.ToTable("QuoteRequests", "sales", t =>
                        {
                            t.HasCheckConstraint("CK_QuoteRequests_Acknowledgment", "[PrivacyNoticeAcknowledged] = 1");

                            t.HasCheckConstraint("CK_QuoteRequests_Code", "LEN([QuoteRequestCode]) = 28 AND [QuoteRequestCode] LIKE 'NQR-%' AND SUBSTRING([QuoteRequestCode], 5, 24) NOT LIKE '%[^0-9A-F]%' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_QuoteRequests_LegalHold", "([LegalHoldStartedAtUtc] IS NULL AND [LegalHoldReviewAtUtc] IS NULL AND [LegalHoldUntilUtc] IS NULL AND [LegalHoldOwnerRef] IS NULL AND [LegalHoldReasonCode] IS NULL AND [LegalHoldTicketRef] IS NULL) OR ([LegalHoldStartedAtUtc] IS NOT NULL AND [LegalHoldReviewAtUtc] IS NOT NULL AND [LegalHoldUntilUtc] IS NOT NULL AND [LegalHoldOwnerRef] IS NOT NULL AND [LegalHoldReasonCode] IS NOT NULL AND [LegalHoldTicketRef] IS NOT NULL)");

                            t.HasCheckConstraint("CK_QuoteRequests_Retention", "[RetentionUntilUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_QuoteRequests_Status", "[Status] = 'New'");
                        });
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompanyBrandProfileEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.CompanyEntity", "Company")
                        .WithOne("BrandProfile")
                        .HasForeignKey("NainConfigurator.Infrastructure.Persistence.CompanyBrandProfileEntity", "CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyBrandProfiles_Companies");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompanyEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.CompanyPrivacyPolicyEntity", "ActivePrivacyPolicy")
                        .WithMany()
                        .HasForeignKey("ActivePrivacyPolicyId", "CompanyId")
                        .HasPrincipalKey("CompanyPrivacyPolicyId", "CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Companies_ActivePrivacyPolicy");

                    b.Navigation("ActivePrivacyPolicy");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompanyPrivacyPolicyEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.CompanyEntity", "Company")
                        .WithMany("PrivacyPolicies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyPrivacyPolicies_Companies");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ProductEntity", "Product")
                        .WithMany("CompatibilityRules")
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CompatibilityRules_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleSourceEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleEntity", "Rule")
                        .WithMany("Sources")
                        .HasForeignKey("CompanyId", "ProductId", "CompatibilityRuleId")
                        .HasPrincipalKey("CompanyId", "ProductId", "CompatibilityRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CompatibilityRuleSources_Rules");

                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ProductOptionEntity", "Option")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId", "ProductOptionId")
                        .HasPrincipalKey("CompanyId", "ProductId", "ProductOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CompatibilityRuleSources_Options");

                    b.Navigation("Option");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleTargetEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleEntity", "Rule")
                        .WithMany("Targets")
                        .HasForeignKey("CompanyId", "ProductId", "CompatibilityRuleId")
                        .HasPrincipalKey("CompanyId", "ProductId", "CompatibilityRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CompatibilityRuleTargets_Rules");

                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ProductOptionEntity", "Option")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId", "ProductOptionId")
                        .HasPrincipalKey("CompanyId", "ProductId", "ProductOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CompatibilityRuleTargets_Options");

                    b.Navigation("Option");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ConfigurationEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Configurations_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ConfigurationPriceComponentEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ConfigurationEntity", "Configuration")
                        .WithMany("PriceComponents")
                        .HasForeignKey("CompanyId", "ConfigurationId")
                        .HasPrincipalKey("CompanyId", "ConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ConfigurationPriceComponents_Configurations");

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ConfigurationSelectionSnapshotEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ConfigurationEntity", "Configuration")
                        .WithMany("Selections")
                        .HasForeignKey("CompanyId", "ConfigurationId")
                        .HasPrincipalKey("CompanyId", "ConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ConfigurationSelections_Configurations");

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.OptionGroupEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ProductEntity", "Product")
                        .WithMany("OptionGroups")
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OptionGroups_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ProductEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.CompanyEntity", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Companies");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ProductOptionEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ProductEntity", "Product")
                        .WithMany("Options")
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductOptions_Products");

                    b.HasOne("NainConfigurator.Infrastructure.Persistence.OptionGroupEntity", "OptionGroup")
                        .WithMany("Options")
                        .HasForeignKey("CompanyId", "ProductId", "OptionGroupId")
                        .HasPrincipalKey("CompanyId", "ProductId", "OptionGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductOptions_OptionGroups");

                    b.Navigation("OptionGroup");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.QuoteNotificationOutboxEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.QuoteRequestEntity", "QuoteRequest")
                        .WithOne("Outbox")
                        .HasForeignKey("NainConfigurator.Infrastructure.Persistence.QuoteNotificationOutboxEntity", "CompanyId", "QuoteRequestId")
                        .HasPrincipalKey("NainConfigurator.Infrastructure.Persistence.QuoteRequestEntity", "CompanyId", "QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuoteNotificationOutbox_QuoteRequests");

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.QuoteRequestEntity", b =>
                {
                    b.HasOne("NainConfigurator.Infrastructure.Persistence.ConfigurationEntity", "Configuration")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ConfigurationId")
                        .HasPrincipalKey("CompanyId", "ConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuoteRequests_Configurations");

                    b.HasOne("NainConfigurator.Infrastructure.Persistence.CompanyPrivacyPolicyEntity", "PrivacyPolicy")
                        .WithMany()
                        .HasForeignKey("CompanyPrivacyPolicyId", "CompanyId")
                        .HasPrincipalKey("CompanyPrivacyPolicyId", "CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuoteRequests_PrivacyPolicies");

                    b.Navigation("Configuration");

                    b.Navigation("PrivacyPolicy");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompanyEntity", b =>
                {
                    b.Navigation("BrandProfile");

                    b.Navigation("PrivacyPolicies");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.CompatibilityRuleEntity", b =>
                {
                    b.Navigation("Sources");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ConfigurationEntity", b =>
                {
                    b.Navigation("PriceComponents");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.OptionGroupEntity", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.ProductEntity", b =>
                {
                    b.Navigation("CompatibilityRules");

                    b.Navigation("OptionGroups");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("NainConfigurator.Infrastructure.Persistence.QuoteRequestEntity", b =>
                {
                    b.Navigation("Outbox")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
