<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../NainConfigurator.Application/NainConfigurator.Application.csproj" />
    <ProjectReference Include="../NainConfigurator.Domain/NainConfigurator.Domain.csproj" />
    <ProjectReference Include="../NainConfigurator.Hosting/NainConfigurator.Hosting.csproj" />
    <ProjectReference Include="../NainConfigurator.Infrastructure/NainConfigurator.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup Condition="Exists('../../../web/dist')">
    <Content
      Include="../../../web/dist/**"
      Link="wwwroot/%(RecursiveDir)%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
