<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../NainConfigurator.Hosting/NainConfigurator.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None
      Update="appsettings*.json"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
